apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
    DB_TYPE: postgresdb
    DB_POSTGRESDB_HOST: "n8npoc.postgres.database.azure.com" # Your PostgesDB host (Get it from Azure Portal as decribed in the documentation)
    DB_POSTGRESDB_PORT: "5432" # Leave Default, Don't change
    DB_POSTGRESDB_DATABASE: postgres  # Leave Default, Don't change if you havn't created any other database
    N8N_PROTOCOL: http  # Leave Default, Don't change if you want to configure in http
    N8N_PORT: "5678"  # Leave Default, Don't change
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "false"   # Leave Default, Don't change
    DB_POSTGRESDB_SSL_ENABLED: "true"   # Leave Default, Don't change
    DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: "false"   # Leave Default, Don't change
